<?xml version="1.0"?>
<package format="3">
  <name>reachy_mini</name>
  <version>0.1.0</version>
  <description>Reachy Mini: End-to-end robot control with vision, motor, and audio</description>
  <depend>motor</depend>
  <depend>vision</depend>
  <depend>audio</depend>
  <depend>asr</depend>
  <depend>tts</depend>
  <depend>vad</depend>
  <depend>llm</depend>
  <depend>mcp</depend>
  <system_depend>opencv-spacemit</system_depend>
  <system_depend check_kind="pkg-config" check_arg="libcjson">libcjson-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="portaudio-2.0">portaudio19-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="sndfile">libsndfile1-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="samplerate">libsamplerate0-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="alsa">libasound2-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="fftw3f">libfftw3-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="libcurl">libcurl4-openssl-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="libgpiod">libgpiod-dev</system_depend>
  <system_depend realm="target" check_kind="pkg-config" check_arg="protobuf">libprotobuf-dev</system_depend>
  <system_depend check_kind="pkg-config" check_arg="libudev">libudev-dev</system_depend>
  <system_depend realm="host" check_kind="command" check_arg="protoc">protobuf-compiler</system_depend>
  <system_depend realm="target" check_kind="pkg-config" check_arg="grpc++">libgrpc++-dev</system_depend>
  <system_depend realm="host" check_kind="command" check_arg="grpc_cpp_plugin">protobuf-compiler-grpc</system_depend>

  <export>
    <build_type>cmake</build_type>
</export>
</package>
