# YOLOv5 目标检测模型配置
model_path: ~/.cache/models/vision/yolov5/yolov5_gesture.q.onnx
test_image: ~/.cache/assets/image/006_test.jpg
label_file_path: assets/labels/gesture.txt
image_size: [640, 640]
class: deploy.yolov5_gesture.YOLOv5_GestureDetector
default_params:
  conf_threshold: 0.8
  iou_threshold: 0.5
  num_threads: 4
  providers:
    - SpaceMITExecutionProvider

